### ISSUE TITLE
jQuery

### ISSUE THREAD

**Issue by chaitra-bhat20** [thesaravanakumar/Cognizant-Early-Engagement#3]
I need answer for this below question. Can anybody help please?

Error Message
Create an HTML page that should display the error status message when the user clicks the button ‘Click to Get the Employee Data’  with the id “btn-id” to load the JSON file ‘employee.json’ does not exist.  Use jquery ajax() to perform the task.  Display the error message “Error Message: Not found” in a div tag with the id ‘err-id’.

 Note:

1. Do not alter the files employee.html
2. Write your code in employee.js file
3. Avoid writing the jQuery 'document ready' method for the proper web page visibility.
4. Do not use 'ES6' features.

**Comment by harikrishnan-creator** [comment]
$("#btn-id").click(function(){
        $.ajax('employee.json',{
             error: function(data,status,xhr){
                  $('#err-id').append("Error Message: Not found");
             }
         });
     });

**Comment by Kabeer279** [comment]
Thanks bro..

**Comment by Harshul-Jain** [comment]
Proposed grade: 0.00 / 100
Result Description
 Fail 1 : Request is not executed
 Fail 2 : You have chosen  the correct URL
 
 how to pass the testcase?
